import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/header";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header/>
          <div className="flex min-h-screen flex-col items-center justify-center pt-4">
            {children}
          </div>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
